FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY producer/ ./producer/
COPY scripts/ ./scripts/
COPY data/ ./data/

ENV PYTHONPATH=/app

CMD ["python", "-u", "producer/producer.py"]
