FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer/ ./consumer/
COPY ml/ ./ml/
COPY data/ ./data/

ENV PYTHONPATH=/app

CMD ["python", "-u", "consumer/consumer.py"]
